### ISSUE TITLE
[BUG] [Failed to execute script and a couple of other issues]

### ISSUE THREAD

**Issue by Salphaella** [iamkroot/ilc-scraper#18]
**Context**
* OS: [Windows 10]
* Install method: [Executable]
* Your location: [outside campus]
* Course URL: [http://a.impartus.com/ilc/#/course/153583/694]
* Lecture range: All(Blank)

**Additional context**
Trying to download entire course vids from impartus, unable to do so. Ocassionally run into errors about the impartus account being locked

**Describe the bug**
Fails to execute the script, and get a bunch of errors relating to lines in the code

**Screenshots**
https://prnt.sc/rugeik

**Program output**
<details>
<summary>Click to see output</summary>
<p>

```
Traceback (most recent call last):
  File "ilc_scrape.py", line 338, in <module>
  File "ilc_scrape.py", line 258, in main
  File "ilc_scrape.py", line 204, in login
KeyError: 'message'
```
</p>
</details>

**Comment by iamkroot** [comment]
This would most likely occur due to invalid password entered by you, or if login is not allowed by Impartus for some other reason. I've made some changes so that the app gracefully fails in this case, since there's nothing more we can do.  
Check out [v0.6.3](https://github.com/iamkroot/ilc-scraper/releases/tag/v0.6.3)
